### PR TITLE
Imported (rules) proposal history

### PR DESCRIPTION
**Pull request by dyokomizo**
Proposals for rules imported from [ApocalypseDAO proposal history](https://alchemy.daostack.io/dao/0x44d55a8492a90640dc6af013657eaf1ac5bc9548/history/)

Modifications from [Token Claim Proposal](https://alchemy.daostack.io/dao/0x44d55a8492a90640dc6af013657eaf1ac5bc9548/proposal/0x7cb904fb2e2942122e28be1fbebf40b2653f8c2ac51630a37e739c8631389e7c) applied on [ApocalypseDAO Friends and Family "Round"](https://alchemy.daostack.io/dao/0x44d55a8492a90640dc6af013657eaf1ac5bc9548/proposal/0xe5db071e16008fc245ab3057791144053bb02ad94ae6d4493892fe1fe4bc6368)

No "REP Bump", "Token Claim Proposal", or "REP Slash" proposals were imported, because they aren't working documents, so they aren't a priority for now.

----

We need more people to review this pull request, specially the original authors.

Once this pull request is reviewed and merged we can ramp up new proposals and improve the state.

### CODE REVIEW

**Comment by perlmutterlabs** [comment]
Looks correct

**Review by perlmutterlabs — APPROVED** [review]

**Comment by perlmutterlabs** [comment]
@dyokomizo are you waiting for review from others before merge?

**Comment by dyokomizo** [comment]
> @dyokomizo are you waiting for review from others before merge?

Honestly I'm using this to gauge how engaged is everyone and then decide in a couple of weeks.

**Comment by dyokomizo** [comment]
Hard forking time.

**Pull request closed without merging**
